global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'donghm@omzcloud.vn'
  smtp_auth_username: 'donghm@omzcloud.vn'
  smtp_auth_identity: 'donghm@omzcloud.vn'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
    # email_configs:
    #   - to: 'jackmaviet@gmail.com'
    #     send_resolved: true
    #     tls_config:
    #       insecure_skip_verify: true
    #     text: "{{ .CommonAnnotations.description }}"
    #     headers:
    #       subject: "[alerting][{{ .Status }}][{{ .GroupLabels.alertname }}]"

    telegram_configs:
      - bot_token: "987654:ABCXYZ"
        api_url: "https://api.telegram.org"
        chat_id: -123456
        parse_mode: ''

    # webhook_configs:
    #   - url: 'https://webhook.site/9e616c9e-73c6-46d2-87b3-22471816aa47'